### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Feodor0090** [Feodor0090/symnovel-ci#1]
### Алгоритм

- [ ] Упаковать JDK
- [ ] Упаковать библиотеки
- [ ] Распаковка JDK и либ
- [ ] Компиляция .java в .class
- [ ] Обработка ошибок
- [ ] Упаковать exe преверифайра
- [ ] Преверифай
- [ ] Копирование `res` в `build`
- [ ] Создание манифеста
- [ ] Сборка jar
- [ ] Выгрузка jar

### Проблемы

- [ ] Ругань на сломанную кодировку (в классах созданных в 2020 году)
- [ ] `a`
- [ ] Ругань на самодельные ассерты
- [ ] Код в `master` сломан
